### ISSUE TITLE
Clojure-related Questions

### ISSUE THREAD

**Issue by smolck** [JetBrains/noria-clj#7]
Hello! I came across this project months ago, but it’s changed since then, and I have a few questions. Is it possible to use this library from Clojure? If so, can anyone give an example of using this library from Clojure (and/or will there be a Clojure example in the repo down the road)?

It appears to me that Kotlin and Java are the main languages of this project; is that right? Will Clojure play any (significant) role here in the future?

Thanks in advance!

**Comment by zajac** [comment]
Hi! It is possible to use it from Clojure now. However the doc is a bit out of date here.
We are migrating to Kotlin with UI library. But nothing stops you from using that from Clojure as well as incremental computations engine. This is how I see it now, but that might change in future.

**Comment by zajac** [comment]
here are some simple tests, that could give you an idea on how to run computations: https://github.com/JetBrains/noria-clj/blob/master/clj/test/noria/thunks_test.clj

**Comment by smolck** [comment]
Thank you! Would a PR be accepted that added a Clojure example, or maybe added a link somewhere to one in another repo? I think I might try creating a simple example project at some point, so I might be able to help out in the Clojure examples area.

**Comment by zajac** [comment]
Sure thing! PRs are welcome.

**Comment by smolck** [comment]
Great! Thanks again for the answers!

**Comment by smolck** [comment]
@zajac I tried using noria-clj with [boot](https://github.com/boot-clj/boot) by adding it as a dependency in my `build.boot` file (using `:source-paths   #{"test" "../noria-clj/clj/clj"}` in the `(set-env!)` section of the file) but after requiring `noria` in my `core.clj` file and running `boot run` I get [this error](https://gist.github.com/smolck/c67ae9dcb834518a19db57300ec73a81). Any ideas why that might be happening? I can provide more info if you need it.

BTW, would it be possible to publish `noria-clj` on [Clojars](https://clojars.org/)? If so, do you know what would need to be done for that to work? It would make things a lot easier to use from Clojure, and I'd like to help with the process as much as possible.
